In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)    
print(a.shape)
print(type(a))
print(a[0], a[1], a[2])

[1 2 3]
(3,)
<class 'numpy.ndarray'>
1 2 3


In [7]:
a[2] = 4
print(a)

[1 2 4]


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(b[0, 0], b[0, 1], b[0, 2]) # preporuceno -> brze je i citljivije
print(b[0][0], b[0][1], b[0][2]) # pravi kopiju reda pa moze dodji do greske prilikom menjanja vrednosti

1 2 3
1 2 3


In [ ]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((2, 2))
print(b)

[[1. 1.]
 [1. 1.]]


In [12]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [13]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [14]:
np.random.seed(0)
e = np.random.random((2, 2)) # preporuceno -> ali je isto sto i e = np.random.rand(2, 2) 
print(e)

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]


In [23]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(f"a = \n{a}\n")

b = a[:2, 1:3] 
print(f"a[:2, 1:3] = b = \n{b}\n")

# odsecanje ne pravi novi niz, vec samo novi pogled na isti niz, tako da promena vrednosti u b menja i a
print(a[0, 1])
b[0, 0] = 20
print(a[0, 1])

a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a[:2, 1:3] = b = 
[[2 3]
 [6 7]]

2
20


In [24]:
a[0, 1] = 2
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
slice_copy = a[:2, 1:3].copy() # pravi novi niz, tako da promena vrednosti u slice_copy ne menja a
print(f"slice_copy = \n{slice_copy}\n")
slice_copy[0, 0] = 20
print(f"a = \n{a}\n")
print(f"slice_copy = \n{slice_copy}\n")

slice_copy = 
[[2 3]
 [6 7]]

a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

slice_copy = 
[[20  3]
 [ 6  7]]



In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(f"x = \n{x}\n")
print(f"y = \n{y}\n")

x = 
[[1. 2.]
 [3. 4.]]

y = 
[[5. 6.]
 [7. 8.]]



In [29]:
print(f"x + y = \n{x + y}\n")
print(f"np.add(x, y) = \n{np.add(x, y)}\n")

x + y = 
[[ 6.  8.]
 [10. 12.]]

np.add(x, y) = 
[[ 6.  8.]
 [10. 12.]]



In [30]:
print(f"x - y = \n{x - y}\n")
print(f"np.subtract(x, y) = \n{np.subtract(x, y)}\n")

x - y = 
[[-4. -4.]
 [-4. -4.]]

np.subtract(x, y) = 
[[-4. -4.]
 [-4. -4.]]



In [31]:
print(f"x * y = \n{x * y}\n")
print(f"np.multiply(x, y) = \n{np.multiply(x, y)}\n")

x * y = 
[[ 5. 12.]
 [21. 32.]]

np.multiply(x, y) = 
[[ 5. 12.]
 [21. 32.]]



In [32]:
print(f"x / y = \n{x / y}\n")
print(f"np.divide(x, y) = \n{np.divide(x, y)}\n")

x / y = 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

np.divide(x, y) = 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]



In [40]:
print(f"np.sqrt(x) = \n{np.sqrt(x)}\n") # ekvivalentno sa print(f"{np.sqrt(x)=}\n")

np.sqrt(x) = 
[[1.         1.41421356]
 [1.73205081 2.        ]]



In [41]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(f"x = \n{x}\n")
print(f"y = \n{y}\n")

x = 
[[1 2]
 [3 4]]

y = 
[[5 6]
 [7 8]]



In [42]:
# matricno mnozenje
print(f"x @ y = \n{x @ y}\n")
print(f"np.matmul(x, y) = \n{np.matmul(x, y)}\n")
print(f"x.dot(y) = \n{x.dot(y)}\n")
print(f"np.dot(x, y) = \n{np.dot(x, y)}\n")

x @ y = 
[[19 22]
 [43 50]]

np.matmul(x, y) = 
[[19 22]
 [43 50]]

x.dot(y) = 
[[19 22]
 [43 50]]

np.dot(x, y) = 
[[19 22]
 [43 50]]



In [43]:
v = np.array([9, 10])
w = np.array([11, 12])

# dot moze da se koristi za skalarani proizvod
print(f"v @ w = \n{v @ w}\n")
print(f"v.dot(w) = \n{v.dot(w)}\n")
print(f"np.dot(v, w) = \n{np.dot(v, w)}\n")

v @ w = 
219

v.dot(w) = 
219

np.dot(v, w) = 
219



In [45]:
import numpy.linalg as la

In [46]:
# Ax = b
A = np.array([[2, 0], [0, 2]])
b = np.array([3.4, 7.8])

In [47]:
A_inv = la.inv(A)
print(f"A_inv = \n{A_inv}\n")

A_inv = 
[[0.5 0. ]
 [0.  0.5]]



In [ ]:
x = A_inv @ b # x = np.matmul(A_inv, b) ili x = A_inv.dot(b) ili x = np.dot(A_inv, b)
print(f"x = \n{x}\n")

x = 
[1.7 3.9]



In [49]:
print(A.dot(x))

[3.4 7.8]
